/* 
 * Gaia-Lite for Cosmos
 *
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2007 {
  #[serde(rename = "min_deposit")]
  min_deposit: Option<Vec<::models::Coin>>,
  #[serde(rename = "max_deposit_period")]
  max_deposit_period: Option<String>
}

impl InlineResponse2007 {
  pub fn new() -> InlineResponse2007 {
    InlineResponse2007 {
      min_deposit: None,
      max_deposit_period: None
    }
  }

  pub fn set_min_deposit(&mut self, min_deposit: Vec<::models::Coin>) {
    self.min_deposit = Some(min_deposit);
  }

  pub fn with_min_deposit(mut self, min_deposit: Vec<::models::Coin>) -> InlineResponse2007 {
    self.min_deposit = Some(min_deposit);
    self
  }

  pub fn min_deposit(&self) -> Option<&Vec<::models::Coin>> {
    self.min_deposit.as_ref()
  }

  pub fn reset_min_deposit(&mut self) {
    self.min_deposit = None;
  }

  pub fn set_max_deposit_period(&mut self, max_deposit_period: String) {
    self.max_deposit_period = Some(max_deposit_period);
  }

  pub fn with_max_deposit_period(mut self, max_deposit_period: String) -> InlineResponse2007 {
    self.max_deposit_period = Some(max_deposit_period);
    self
  }

  pub fn max_deposit_period(&self) -> Option<&String> {
    self.max_deposit_period.as_ref()
  }

  pub fn reset_max_deposit_period(&mut self) {
    self.max_deposit_period = None;
  }

}



