/* 
 * Gaia-Lite for Cosmos
 *
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2002 {
  #[serde(rename = "tx")]
  tx: Option<String>
}

impl InlineResponse2002 {
  pub fn new() -> InlineResponse2002 {
    InlineResponse2002 {
      tx: None
    }
  }

  pub fn set_tx(&mut self, tx: String) {
    self.tx = Some(tx);
  }

  pub fn with_tx(mut self, tx: String) -> InlineResponse2002 {
    self.tx = Some(tx);
    self
  }

  pub fn tx(&self) -> Option<&String> {
    self.tx.as_ref()
  }

  pub fn reset_tx(&mut self) {
    self.tx = None;
  }

}



