/* 
 * Gaia-Lite for Cosmos
 *
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2003 {
  #[serde(rename = "type")]
  _type: Option<String>,
  #[serde(rename = "value")]
  value: Option<::models::InlineResponse2003Value>
}

impl InlineResponse2003 {
  pub fn new() -> InlineResponse2003 {
    InlineResponse2003 {
      _type: None,
      value: None
    }
  }

  pub fn set__type(&mut self, _type: String) {
    self._type = Some(_type);
  }

  pub fn with__type(mut self, _type: String) -> InlineResponse2003 {
    self._type = Some(_type);
    self
  }

  pub fn _type(&self) -> Option<&String> {
    self._type.as_ref()
  }

  pub fn reset__type(&mut self) {
    self._type = None;
  }

  pub fn set_value(&mut self, value: ::models::InlineResponse2003Value) {
    self.value = Some(value);
  }

  pub fn with_value(mut self, value: ::models::InlineResponse2003Value) -> InlineResponse2003 {
    self.value = Some(value);
    self
  }

  pub fn value(&self) -> Option<&::models::InlineResponse2003Value> {
    self.value.as_ref()
  }

  pub fn reset_value(&mut self) {
    self.value = None;
  }

}



