/* 
 * Gaia-Lite for Cosmos
 *
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Proposer {
  #[serde(rename = "proposal_id")]
  proposal_id: Option<i32>,
  #[serde(rename = "proposer")]
  proposer: Option<String>
}

impl Proposer {
  pub fn new() -> Proposer {
    Proposer {
      proposal_id: None,
      proposer: None
    }
  }

  pub fn set_proposal_id(&mut self, proposal_id: i32) {
    self.proposal_id = Some(proposal_id);
  }

  pub fn with_proposal_id(mut self, proposal_id: i32) -> Proposer {
    self.proposal_id = Some(proposal_id);
    self
  }

  pub fn proposal_id(&self) -> Option<&i32> {
    self.proposal_id.as_ref()
  }

  pub fn reset_proposal_id(&mut self) {
    self.proposal_id = None;
  }

  pub fn set_proposer(&mut self, proposer: String) {
    self.proposer = Some(proposer);
  }

  pub fn with_proposer(mut self, proposer: String) -> Proposer {
    self.proposer = Some(proposer);
    self
  }

  pub fn proposer(&self) -> Option<&String> {
    self.proposer.as_ref()
  }

  pub fn reset_proposer(&mut self) {
    self.proposer = None;
  }

}



