/* 
 * Gaia-Lite for Cosmos
 *
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Tx {
  #[serde(rename = "tx")]
  tx: Option<::models::StdTx>
}

impl Tx {
  pub fn new() -> Tx {
    Tx {
      tx: None
    }
  }

  pub fn set_tx(&mut self, tx: ::models::StdTx) {
    self.tx = Some(tx);
  }

  pub fn with_tx(mut self, tx: ::models::StdTx) -> Tx {
    self.tx = Some(tx);
    self
  }

  pub fn tx(&self) -> Option<&::models::StdTx> {
    self.tx.as_ref()
  }

  pub fn reset_tx(&mut self) {
    self.tx = None;
  }

}



