/* 
 * Gaia-Lite for Cosmos
 *
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TxBroadcast {
  #[serde(rename = "tx")]
  tx: Option<::models::StdTx>,
  #[serde(rename = "mode")]
  mode: Option<String>
}

impl TxBroadcast {
  pub fn new() -> TxBroadcast {
    TxBroadcast {
      tx: None,
      mode: None
    }
  }

  pub fn set_tx(&mut self, tx: ::models::StdTx) {
    self.tx = Some(tx);
  }

  pub fn with_tx(mut self, tx: ::models::StdTx) -> TxBroadcast {
    self.tx = Some(tx);
    self
  }

  pub fn tx(&self) -> Option<&::models::StdTx> {
    self.tx.as_ref()
  }

  pub fn reset_tx(&mut self) {
    self.tx = None;
  }

  pub fn set_mode(&mut self, mode: String) {
    self.mode = Some(mode);
  }

  pub fn with_mode(mut self, mode: String) -> TxBroadcast {
    self.mode = Some(mode);
    self
  }

  pub fn mode(&self) -> Option<&String> {
    self.mode.as_ref()
  }

  pub fn reset_mode(&mut self) {
    self.mode = None;
  }

}



