/* 
 * Gaia-Lite for Cosmos
 *
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ValidatorAddress : bech32 encoded address

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ValidatorAddress {
}

impl ValidatorAddress {
  /// bech32 encoded address
  pub fn new() -> ValidatorAddress {
    ValidatorAddress {
    }
  }

}



