/* 
 * Gaia-Lite for Cosmos
 *
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct WithdrawRequestBody2 {
  #[serde(rename = "base_req")]
  base_req: Option<::models::BaseReq>,
  #[serde(rename = "withdraw_address")]
  withdraw_address: Option<::models::Address>
}

impl WithdrawRequestBody2 {
  pub fn new() -> WithdrawRequestBody2 {
    WithdrawRequestBody2 {
      base_req: None,
      withdraw_address: None
    }
  }

  pub fn set_base_req(&mut self, base_req: ::models::BaseReq) {
    self.base_req = Some(base_req);
  }

  pub fn with_base_req(mut self, base_req: ::models::BaseReq) -> WithdrawRequestBody2 {
    self.base_req = Some(base_req);
    self
  }

  pub fn base_req(&self) -> Option<&::models::BaseReq> {
    self.base_req.as_ref()
  }

  pub fn reset_base_req(&mut self) {
    self.base_req = None;
  }

  pub fn set_withdraw_address(&mut self, withdraw_address: ::models::Address) {
    self.withdraw_address = Some(withdraw_address);
  }

  pub fn with_withdraw_address(mut self, withdraw_address: ::models::Address) -> WithdrawRequestBody2 {
    self.withdraw_address = Some(withdraw_address);
    self
  }

  pub fn withdraw_address(&self) -> Option<&::models::Address> {
    self.withdraw_address.as_ref()
  }

  pub fn reset_withdraw_address(&mut self) {
    self.withdraw_address = None;
  }

}



